### TEST HTTP
#

@place=Marks%20Kommun
@gorest_url=https://gorest.co.in/public/v2

### Dummy POST Test
POST http://localhost:12345/echobody
Content-Type: application/json
Accept: application/json
Authorization: Bearer ACCESS-TOKEN

data





###
#
#
{
    "name":"Inghe Brahe",
    "korv":"spad"
}

### Users
GET {{gorest_url}}

### Create user
POST {{gorest_url}}/users
Content-Type: application/json
Accept: application/json
Authorization: Bearer ACCESS-TOKEN

{
    "name":"Tenali Ramakrishna",
    "gender":"male",
    "email":"tenali.ramakrishna@15ce.com",
    "status":"active"
}


### @name Weather
GET wttr.in/{{place}}

### @name Rain
GET v2.wttr.in/Marks%20Kommun

### @name Sunet
GET https://sunet.se

### @name Poke 1
@base_poke=https://pokeapi.co/api/v2/pokemon
@pokemon=pikachu
@pokemon2=bulbasaur

GET {{base_poke}}/{{pokemon}} HTTP/1.1
Accept: application/json

### @name Poke 2
GET {{base_poke}}/{{pokemon2}} HTTP/1.1
Accept: application/json


